# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory within the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container at /app
COPY index.html /app/web_app
COPY mock_api_data.py /app/mock_api

# Expose ports for the web app and mock API
EXPOSE 8000 5000

# Define the command to run when the container starts
CMD ["python mock_api_data.py", "python -m http.server"]